### ISSUE TITLE
Add support for fasthttp

### ISSUE THREAD

**Issue by valyala** [urfave/negroni#105]
It would be great if negroni will support [fasthttp](https://github.com/valyala/fasthttp) additionally to standard [net/http](https://golang.org/pkg/net/http/).

**Comment by panjunjie** [comment]
支持一下，好厉害！可惜作者好久没有来了！

**Comment by pjebs** [comment]
+1

**Comment by pjebs** [comment]
+1^inf

**Comment by jszwedko** [comment]
I'm not sure about implementing a middleware library for `fasthttp` in `negroni` proper since the interface is pretty disparate (and would end up pulling in `fasthttp` as a dependency). Perhaps this makes more sense as a separate library? Or, at the least, a separate package so that users can only include the interface they need.

**Comment by meatballhat** [comment]
@valyala Much like @jszwedko asked, how viable do you think an external library might be to solve this?  Perhaps such a library could use the handler converter that comes with fasthttp?

**Comment by valyala** [comment]
@meatballhat , this sounds reasonable to me.

**Comment by rizkyramadhan** [comment]
Hi, 2 years later... is there any progress on this issue ? can we use fasthttp with negroni ?

**Comment by Festum** [comment]
@jszwedko This issue should be closed

**Comment by jszwedko** [comment]
Thanks for the bump! I still believe this would make the most sense as a separate library given the difference in interfaces from the standard `net/http`.

I'll close this out, but I'm happy to add a link to the README if/when a similar library is created for `fasthttp`.
