### ISSUE TITLE
Best Practice

### ISSUE THREAD

**Issue by pjebs** [urfave/negroni#135]
This is gorilla mux question more than negroni:

Which is better practice from a garbage collection/memory management Point of View:

Setting the handler like this:

`appRoutes.Methods("GET").Path("/customer/\").HandlerFunc(cAc.CreateCode)`

```
func CreateCode(w http.ResponseWriter, r *http.Request) {
...
}
```

OR like this

```
func Handler1() func(http.ResponseWriter, *http.Request) {
    return func(w http.ResponseWriter, r *http.Request) {
        fmt.Fprint(w, "/api -> Handler1 - protected by RestGate (Static Mode)\n")
    }
}
```

**Comment by pjebs** [comment]
I'm only speculating, but I feel in option A, the CreateCode function is ALWAYS kept in memory the entire time.
In Option B, Handler1() is kept in memory the whole time but the inner closure is not and is generated dynamically.

**Comment by hexadecy** [comment]
So the first one is probably faster, also Go compiler inline small functions a lot. 
You should probably worry more about contex passing.

**Comment by jszwedko** [comment]
Hi @pjebs!

While an interesting question, I don't think the issues section of this repository is the best place to discuss it. I might suggest Stackoverflow, [the google group](https://groups.google.com/forum/#!forum/golang-nuts), or #go-nuts on Freenode since this is more focused on Go the language than any of the libraries involved.

Going to close this out, but let me know if you disagree!
