### ISSUE TITLE
Feature request : display url arguments in Logger middleware

### ISSUE THREAD

**Issue by harobed** [urfave/negroni#136]
Hi,

this is a feature request : display url arguments in Logger middleware.

Best regards,
Stéphane

**Comment by jszwedko** [comment]
Hi @harobed,

I assume you mean the `GET` parameters?

**Comment by jszwedko** [comment]
Doh, missed the link to #137

**Comment by agnivade** [comment]
We should change `r.URL.Path` to `r.RequestURI`. That captures everything.

Also, we should add -
- r.UserAgent()
- r.Referer()
- r.RemoteAddr

and just store these in the LoggerEntry struct. Since the `LoggerDefaultFormat` is exported, the user can choose to add these extra variables. That way, the external behavior is unchanged.

If you agree with this, may I send a PR for it ?

**Comment by jszwedko** [comment]
:+1: I wonder if it makes sense to just pass the whole `http.Request` struct to the template.

**Comment by agnivade** [comment]
Not a bad idea, except we would lose the template format string used to log. And, also I wanted log `UserAgent()` and `Referer()`, both of which are functions, not properties. Or can we specify function calls of structs from inside templates ? Is this valid - `{{.Request.UserAgent()}}` ?

**Comment by jszwedko** [comment]
You can call methods on template values in the same manner as properties (`{{ .Request.UserAgent }}` in your example).

I think we should keep the existing properties for compatibility, but possible also add `Request` as an available field to allow people the flexibility to log arbitrary fields.

**Comment by agnivade** [comment]
Great ! PR incoming soon !
