### ISSUE TITLE
New version tag

### ISSUE THREAD

**Issue by tapir** [urfave/negroni#218]
The latest version tag v0.3.0 is from Nov 2017. Can we get a new one please?

**Comment by agnivade** [comment]
ping @jszwedko. I just stumbled on this with 1.11.

This will be a major issue with the just released 1.11 if we don't cut a new release. 1.11 in module mode, will by default, take the newest tag. Which in this case is about 186 commits old from master.

Kindly cut a new release. Or else, we are forced to set `@master` in our go.mod files.

**Comment by jszwedko** [comment]
:+1: I took this opportunity to _finally_ tag `negroni` as `1.0.0` :confetti_ball: 

Notably, there was only one code change (#223) from the previous tag, `v0.3.0`. @agnivade I think you may have been looking at `v0.2.0` since I neglected to fill in the release notes for `v0.3.0`.

Thanks for the bump and apologies for the delay in cutting this.
